spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Srinu@155
    type: org.apache.commons.dbcp2.BasicDataSource
    url: jdbc:mysql:///ntspbms615db
    username: root
