spring: 
   profiles: 
      active: prod
---
spring: 
  profiles: dev
  
  
  
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   password: Srinu@155
   type: org.apache.commons.dbcp2.BasicDataSource
   url: jdbc:mysql:///ntspbms615db
   username: root
---
spring: 
   profiles: test
   
   
   datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Srinu@155
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:mysql:///ntspbms615db
    username: root
--- 
  spring: 
     profiles: uat
     
     datasource:
       driver-class-name: oracle.jdbc.driver.OracleDriver
       password: Srinu@155
       url: jdbc:oracle:thin:@localhost:1521:orcl
       username: system
--- 
   spring: 
      profiles: prod
      
      
      datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        password: Srinu@155
        url: jdbc:oracle:thin:@localhost:1521:orcl
        username: system


     
     
     